### ISSUE TITLE
Push a tag for v1.0.1 to pick up the LICENSE and go.mod change

### ISSUE THREAD

**Issue by joepurdy** [segmentio/backo-go#8]
In order to allow tooling to detect that this project is MIT licensed following the changes to resolve #7 a maintainer needs to tag the latest commit as v1.0.1 and push that tag. See: https://go.dev/doc/modules/publishing

Once this has been done license scanning tools and resources like https://pkg.go.dev/github.com/segmentio/backo-go will update to properly reflect the module as MIT licensed.

**Comment by achille-roussel** [comment]
I pushed v1.0.1, thanks for the report 👍
